### PR TITLE
Addresses #686 Clarifying the meaning/usage of expresses

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #686 Clarifying the meaning/usage of expresses

### CODE REVIEW

**Review by dosumis — APPROVED** [review]
Looks good to me. There are some small syntactic changes, presumably due to Protege /OWL-API version - but I'm confident that they are harmless ordering issues, so happy to merge.

**Comment by wdduncan** [comment]
Great. I'll put it on the RO call agenda for tomorrow.

**Comment by bvarner-ebi** [comment]
> Great. I'll put it on the RO call agenda for tomorrow.

@wdduncan, do you prefer that this is merged after the call or OK to squash and merge now?

**Review by cmungall — APPROVED** [review]

**Comment by cmungall** [comment]
ready to merge!

**Pull request merged**
