### PR TITLE
Add relation chain 'process has causal agent' o 'in taxon' -> 'in taxon'

### LINKED ISSUE #409: 'process has causal agent' : add property chain for 'in taxon'

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #409.

### CODE REVIEW

**Comment by wdduncan** [comment]
Hi @balhoff.  
Sorry, if I'm coming late to the party :)  
Can you clarify what the domain and range are of `process has causal agent` are?  The definition in `ro-edit.owl` seems (to me) to indicate that the domain is a process and the range is material entity. If so we have:

Let **p** be a process, **m** be a material entity, and **t.** the target taxon Then I think the chain role would imply:

**p** `process has causal` **m** `in taxon` ->  **p** `in taxon` **t**

Are you wanting to say that process **p** is in taxon **t**?

Apologies if I am not understanding the intent or logic involved.

**Comment by balhoff** [comment]
Hi @wdduncan, this change is to address a specific issue in GO: https://github.com/geneontology/go-ontology/issues/17613#issuecomment-720491074

We do want to infer that the process p is in taxon t. Since this came from a GO requirement, I wanted to make sure a couple other people reviewed to catch any cases where this might not hold generally.

**Comment by dosumis** [comment]
Does GO still have multi-organism processes that are multi-species (e.g. for symbiosis)?  Inference may not be safe in these cases.

**Comment by wdduncan** [comment]
thanks @balhoff 

The definition for `in taxon` reads:
```
x is in taxon y if an only if y is an organism, and the relationship between x and y is one of: part of (reflexive), developmentally preceded by, derives from, secreted by, expressed.
```
If processes can be the the domain the `in taxon` will you need to update the definition?

**Comment by balhoff** [comment]
> If processes can be the the domain the in taxon will you need to update the definition?

I didn't realize that was in the 'in taxon' definition. Processes are already widely used in the domain of 'in taxon', so I think that's a separate issue to address.

**Review by dosumis — CHANGES_REQUESTED** [review]
May not be safe given that some processes may have causal agents in multiple species - e.g.- root nodule formation.  This may already apply to terms in GO.

**Comment by balhoff** [comment]
Thanks @dosumis! We'll discuss at a GO call.

**Comment by balhoff** [comment]
We agreed at the GO call on 2020-12-14 that this is not general, so I'll close this.

**Pull request closed without merging**
