### PR TITLE
NTR: Add conjugate acid and base relations

### LINKED ISSUE #643: Add conjugate relations from CHEBI and include transitive versions
CHEBI includes a number of relations that are very useful for queries, in particular conjugate base/acid relations

In CHEBI these have no associated logical axioms other than inverse_of (which of course in OWL obtains on the instance level - chebi makes reciprocal assertions)

```
    <!-- http://purl.obolibrary.org/obo/chebi#is_conjugate_acid_of -->

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/chebi#is_conjugate_acid_of">
        <owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of"/>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">chebi_ontology</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">is_conjugate_acid_of</oboInOwl:id>
        <oboInOwl:is_cyclic rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</oboInOwl:is_cyclic>
        <oboInOwl:is_transitive rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</oboInOwl:is_transitive>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">is conjugate acid of</rdfs:label>
    </owl:ObjectProperty>



    <!-- http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of -->

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of">
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">chebi_ontology</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">is_conjugate_base_of</oboInOwl:id>
        <oboInOwl:is_transitive rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</oboInOwl:is_transitive>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">is conjugate base of</rdfs:label>
    </owl:ObjectProperty>
```

there is no documentation on these in the OWL, but there is a [section in the chebi user guide](https://docs.google.com/document/d/1_w-DwBdCCOh1gMeeP6yqGzcnkpbHYOa3AGSODe5epcg/edit#heading=h.hnsqoqu978s5) that details their use:

image

We should coordinate with CHEBI such that there is OWL for these relations that have full documentation

Additionally, these are not transitive in CHEBI - they are used to query the direct conjugate. It would be useful to have transitive versions.

### PR DESCRIPTION
**Pull request by cthoyt**
This PR closes #643 by adding five relationships:

| CURIE | Label | Reason |
|-------|------|------|
| RO:0018034 | is protonated form of | Transitive relationship, mirrors http://purl.obolibrary.org/obo/chebi#is_conjugate_acid_of |
| RO:0018033 | is deprotonated form of | Transitive relationship, mirrors http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of |
| RO:0018032 | is direct conjugate acid of | Corresponds to a one proton change, not transitive. |
| RO:0018031 | is direct conjugate base of | Corresponds to a one proton change, not transitive. | 
| RO:0018030 | chemical relationship | Groups the previous two relations, and can be used to group future relations ported out of [the ChEBI handbook](https://docs.google.com/document/d/1_w-DwBdCCOh1gMeeP6yqGzcnkpbHYOa3AGSODe5epcg/edit#), similarly to how [disease relationship (RO:0040035)](http://purl.obolibrary.org/obo/RO_0040035) groups various disease relationships. If this is too general, we could rename it to `in protonation relationship with` |

This PR does **not** port the `oboInOwl:is_cyclic` and `oboInOwl:is_transitive` that were originally in the ChEBI RDF based on suggestions from Jim.

This PR uses the design pattern described in https://oborel.github.io/obo-relations/direct-and-indirect-relations/

### CODE REVIEW

**Review by balhoff — CHANGES_REQUESTED** [review]
I don't think we should add an annotation property `oboInOwl:is_transitive`. We already have a way to declare transitive properties in OWL.

`oboInOwl:is_cyclic` is also part of the OBO file format and probably shouldn't be an annotation property, although I don't know what its meaning is.

**Comment by cthoyt** [comment]
@balhoff thanks for the feedback. I'm happy to remove these - I just wanted to bring these from the ChEBI RDF to make it maximally compatible. No problem to remove these (i'm also not aware of what `is_cyclic` means)

**Comment by cmungall** [comment]
See my comments on transitivity on the original issue - this is nuanced, we should try and get consensus on this first

**Comment by ddooley** [comment]
Discussed on Jan 31 call: This pull request involves intransitive versions and so is fine to go as is, but labels then may have different semantics from CHEBI's versions. @cthoyt could you contact CHEBI about whether they can adjust/clarify transitive versions?  If they are able to respond quickly then that would proactively prepare for this relationship change, and their adoption of it.

Jie suggests editor note that transitivity was removed from these relations in case others have been using CHEBI version.

Previously discussed on Jan 3 2023.

**Comment by cthoyt** [comment]
@ddooley will do! Sorry I couldn't attend tonight and give an update. I'll reach out to @amalik01 by email and report back on what he says ASAP

**Comment by cthoyt** [comment]
Got generally positive feedback from Adnan Malik (ChEBI) and Andrew R Leach (Rhea) but this is not necessarily a priority for them during the ChEBI 2.0 project. We're still waiting to hear some feedback from Chris's discussion with Alan Bridge and the Rhea team, then this can probably move forwards.

**Comment by cmungall** [comment]
unfortunately I did not get a chance to discuss

**Review by balhoff — APPROVED** [review]
I take it back; @matentzn says we will address the DC elements issues for the whole ontology separately.

**Comment by cthoyt** [comment]
Great, I was thinking we could add some sparql validations for this.

**Comment by matentzn** [comment]
There was no further concern with this PR, but see #691

**Pull request merged**
