### PR TITLE
Converted edit file to functional syntax, fixes #207

### LINKED ISSUE #207: Move ro-edit.owl to functional syntax
1. This would give much more usable diffs & the possibility to fix clashes by hand if required.

2. Now we're using 'branch - pull - merge' regularly with RO, can we move the master to functional syntax + have some guidance on what OWL-API versions serialised in a way that is safe to use with merging?  Merge with rdf xml makes me very nervous and the git-owl-tools appears to be broken https://github.com/ShahimEssaid/git-owl-tools/issues/4

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
```
$ git pull
Already up-to-date.
$ robot convert -i ro-edit.owl -o ro-edit.ofn
$ mv ro-edit.ofn ro-edit.owl
$ git diff
gitowl     
gitowl ||  Diffing:  src/ontology/ro-edit.owl
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0000052 
gitowl --  SubAnnotationPropertyOf(obo:RO_0000052 obo:RO_0002314)
gitowl ||      RO_0000052 SubPropertyOf inheres in part of
gitowl ++  SubObjectPropertyOf(obo:RO_0000052 obo:RO_0002314)
gitowl ||      RO_0000052 SubPropertyOf inheres in part of
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002000 
gitowl --  SubAnnotationPropertyOf(obo:RO_0002000 obo:RO_0002323)
gitowl ||      RO_0002000 SubPropertyOf mereotopologically related to
gitowl ++  SubObjectPropertyOf(obo:RO_0002000 obo:RO_0002323)
gitowl ||      RO_0002000 SubPropertyOf mereotopologically related to
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002002 
gitowl --  SubAnnotationPropertyOf(obo:RO_0002002 obo:RO_0002323)
gitowl ||      RO_0002002 SubPropertyOf mereotopologically related to
gitowl ++  SubObjectPropertyOf(obo:RO_0002002 obo:RO_0002323)
gitowl ||      RO_0002002 SubPropertyOf mereotopologically related to
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002022 
gitowl --  AnnotationAssertion(rdfs:comment obo:RO_0002022 "Process(P2) is directly regulated by process(P1) iff: P1 regulates P2 via direct physical interaction between an agent executing P1 (
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002022> comment "Process(P2) is directly regulated by process(P1) iff: P1 regulates P2 via direct physical interaction between an agent execut
gitowl ++  AnnotationAssertion(Annotation(oboInOwl:hasDbXref "GOC:dos") rdfs:comment obo:RO_0002022 "Process(P2) is directly regulated by process(P1) iff: P1 regulates P2 via direct physical in
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002022> comment "Process(P2) is directly regulated by process(P1) iff: P1 regulates P2 via direct physical interaction between an agent execut
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002023 
gitowl --  AnnotationAssertion(obo:IAO_0000115 obo:RO_0002023 "Process(P2) is directly negatively regulated by process(P1) iff: P1 negatively regulates P2 via direct physical interaction betwee
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002023> IAO_0000115 "Process(P2) is directly negatively regulated by process(P1) iff: P1 negatively regulates P2 via direct physical interacti
gitowl ++  AnnotationAssertion(Annotation(oboInOwl:hasDbXref "GOC:dos") obo:IAO_0000115 obo:RO_0002023 "Process(P2) is directly negatively regulated by process(P1) iff: P1 negatively regulates 
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002023> IAO_0000115 "Process(P2) is directly negatively regulated by process(P1) iff: P1 negatively regulates P2 via direct physical interacti
gitowl ||   
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002024 
gitowl --  AnnotationAssertion(obo:IAO_0000115 obo:RO_0002024 "Process(P2) is directly postively regulated by process(P1) iff: P1 positively regulates P2 via direct physical interaction between
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002024> IAO_0000115 "Process(P2) is directly postively regulated by process(P1) iff: P1 positively regulates P2 via direct physical interactio
gitowl ++  AnnotationAssertion(Annotation(oboInOwl:hasDbXref "GOC:dos") obo:IAO_0000115 obo:RO_0002024 "Process(P2) is directly postively regulated by process(P1) iff: P1 positively regulates P
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002024> IAO_0000115 "Process(P2) is directly postively regulated by process(P1) iff: P1 positively regulates P2 via direct physical interactio
gitowl     
```

**Comment by cmungall** [comment]
image

The functional syntax is unambiguously correct, it's odd that it shows it was previously an annotation property. One more reason why an OWL syntax is best for source.

image

not sure why it's showing it as previously unannotated. I think just a quirk of git-owl-diff. 

This confirms that the annotation was there and the functional syntax is correct
https://github.com/oborel/obo-relations/blob/3db0e1f7d7629cc96d33d1ca009c99771326a1c3/src/ontology/ro-edit.owl#L1314-L1329

**Comment by dosumis** [comment]
I've done this independently - directly on master:
https://github.com/oborel/obo-relations/commit/15bb5ee15ae209d5f6752c5b50e32e5541b38518

(Seemed too much of a pain to do as pull request given that diffs etc would make no sense).

**Comment by cmungall** [comment]
closing as @dosumis had more edits

**Pull request closed without merging**
