### PR TITLE
Bridge BFO role to CHEBI role.

### PR DESCRIPTION
**Pull request by balhoff**
Addresses issue #467. This is also taken care of by the range declaration for [has role](http://purl.obolibrary.org/obo/RO_0000087), however we are still not applying range reasoning in very many places due to most people still using ELK 0.4.3.

### CODE REVIEW

**Comment by matentzn** [comment]
Is RO the right place for this kind of alignment? I would imagine that once we move to ODK, much of this kind of axiomatisation should move to COB, right? In any case, I think its the right move, but this is probably one for @cmungall to judge.

**Comment by matentzn** [comment]
Also: since our CI pipelines use Elk 0.4.3, this wont really solve our "role part of material entity" problem, right?

**Comment by balhoff** [comment]
> Also: since our CI pipelines use Elk 0.4.3, this wont really solve our "role part of material entity" problem, right?

This is meant to solve that, at least in part. `has role` has a range axiom that would make this less needed if the reasoner supported ranges.

**Comment by balhoff** [comment]
Changed to be subclass of PATO:quality, which is what I think is meant by "characteristic" above.

**Comment by cmungall** [comment]
correct https://github.com/OBOFoundry/COB/blob/master/src/ontology/components/cob-to-external.tsv#L120

**Pull request merged**
