### PR TITLE
Revert previous committed changes made in PR #672 and add missing axioms for `has roost`

### PR DESCRIPTION
**Pull request by wdduncan**
Reverts oborel/obo-relations#672

### CODE REVIEW

**Comment by wdduncan** [comment]
@matentzn I've done the revert

**Comment by anitacaron** [comment]
Why was this PR not merged? This is fixing all issues!

**Comment by wdduncan** [comment]
There has been a lot of activity. I don't know if this PR is needed.

**Comment by gouttegd** [comment]
@wdduncan  My understanding is that #672, in addition to introducing _breaking changes_ (invalid changes that were correctly detected by the test suite and that prevented RO from being successfully built), also introduced other changes that didn’t trigger any failure in the test suite (they didn’t violate any rules) but were nonetheless incorrect.

The breaking changes were all fixed by by #731 (allowing all CI checks to pass), but the other, non-breaking changes, being undetectable by the test suite, were not. This is what @anitacaron is now addressing by re-opening this PR.

**Comment by wdduncan** [comment]
Thanks @gouttegd

**Comment by anitacaron** [comment]
All the work done didn't revert any of the reverts that this PR is doing. For instance, this rollback of the changes made in the PRs since Jan 18 because of commit https://github.com/oborel/obo-relations/pull/672/commits/875a4572a8213197c86e548dff97dba72b69aa54 made without updating first from the master.

**Review by gouttegd — APPROVED** [review]

**Comment by matentzn** [comment]
This is really really really horrendous.. I hope with the new branch protection rules this will never happen again.

**Comment by gouttegd** [comment]
> I hope with the new branch protection rules this will never happen again.

The kind of unwanted changes here (such as the revert to CARO terms instead of UBERON terms in some places) would not have been caught by the CI checks, so merely preventing merging until CI checks have passed will _not_ prevent that.

**Comment by anitacaron** [comment]
There're other preventions in place now. The PR needs two approvals, and a new commit after approval will dismiss it.

**Pull request merged**
