### PR TITLE
Clean up files

### LINKED ISSUE #682: Post ODK Migration Clean up
Figure out what to do with these, I think they are not used at all:

- [ ] https://github.com/oborel/obo-relations/blob/master/bfo-classes-minimal.owl
- [ ] https://github.com/oborel/obo-relations/blob/master/bfo-axioms.owl
- [ ] https://github.com/oborel/obo-relations/blob/master/CHANGES.md
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/CHANGES
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/README.txt
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/omo_import.owl
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/other_import.ofn
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/cut-release.sh
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-diff.html
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-diff.md
- [ ] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro_bfo_1_2_bridge.owl (careful)

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #682

 - [ ] https://github.com/oborel/obo-relations/blob/master/bfo-classes-minimal.owl
 - [ ] https://github.com/oborel/obo-relations/blob/master/bfo-axioms.owl

They were moved to `src/ontology/components` in the ODK Migration.

- [X] https://github.com/oborel/obo-relations/blob/master/CHANGES.md
- [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/CHANGES
- [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/README.txt

I kept the changes files for historical purposes.

 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/omo_import.owl
 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/other_import.ofn

Moved to `src/ontology/imports` during ODK Migration.

 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/cut-release.sh
 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-diff.html
 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-diff.md

Removed.

 - [X] https://github.com/oborel/obo-relations/blob/master/src/ontology/ro_bfo_1_2_bridge.owl (careful)

Not used as import in anywhere. Moved to `src/ontology/attic` where other similiar files lives.

### CODE REVIEW

**Comment by wdduncan** [comment]
The BFO classes no longer have labels. E.g.:

image

Are you moving the BFO classes to another import? They should not be deleted if they are being used.

**Comment by anitacaron** [comment]
The files I removed are at the root level. The same files are in the `src/ontology/components`.

It's not showing the labels because it's missing the declaration of these files in the catalog. Damien has fixed that in [this commit](https://github.com/oborel/obo-relations/pull/709/commits/25cfbdf631a431720fa5faa2edba3c80bf7d4554).

**Review by matentzn — CHANGES_REQUESTED** [review]
Keep bfo-axioms and bfo-classes-minimal as they are, the rest is fine!

**Review by matentzn — APPROVED** [review]

**Comment by cthoyt** [comment]
this is really really bad, look at the commit history

Screenshot 2023-06-26 at 23 04 38

we have a commit to the main branch that breaks it. then this one on top of it, adding to the issues. I think we need to hard reset to 2 commits on master ago to the last non-broken commit and immediately enforce protection on main branch
 that CI has to pass

**Pull request merged**
