### PR TITLE
DO NOT MERGE YET First pass at #68 making a ro-chado subset

### PR DESCRIPTION
**Pull request by cmungall**
cc @cybersiddhu

### CODE REVIEW

**Comment by kimrutherford** [comment]
> ro-chado.obo is quite a bit smaller than the ro.obo in the master branch

Looks like that's due to --remove-tbox so please ignore that.

**Comment by cybersiddhu** [comment]
I have to make few minor changes to make it work ...
* Skipped `OBO_REL` as backward compatibility is not a concern for me. https://github.com/dictyBase/obo-relations/commit/1182284b6a098c83843dea13cbe7a448027dc193
* Filtered out `remark` and `property_value` headers. Not seems to be needed for chado and secondly it chokes the [OBO parser](https://metacpan.org/release/ONTO-PERL) https://github.com/dictyBase/obo-relations/commit/136e28c4aaccbcf33c76c8e27c164be0f70b3ac5

Anyway, are you planning to merge this to master.

**Comment by kimrutherford** [comment]
We have used ro-chado.obo to do a full load of Chado for PomBase and it all looks fine.  So the next PomBase release will be based in it.

**Comment by cybersiddhu** [comment]
Nice work kim, great to know that.

Chris, 
Are you thinking about doing any merge or you expect more work need to be done.

**Comment by cmungall** [comment]
Sounds like we should merge

@cybersiddhu - do you want to to merge first, then you make a PR with yr changes (which look fine)

**Comment by cmungall** [comment]
in latest release, https://github.com/oborel/obo-relations/releases/tag/v2016-06-15

The PURL is
http://purl.obolibrary.org/obo/ro/subsets/ro-chado.obo

@cybersiddhu can you make a new PR with your changes?

Should we announce on GMOD?

**Comment by cybersiddhu** [comment]
Chris,
Thanks for the release.
One of my commit removes the `OBO_REL` backward compatibility, so i will skip that one. 
Yes it should be announced to GMOD list, should be a good time as gmod meeting is very close. More people might try it out and get more feedback.

**Pull request merged**
