### PR TITLE
New synapsing relationships

### LINKED ISSUE #455: Subproperties of 'synapsed to' and 'synapsed by'
Relationships to be used where there is a more meaningful number of synapses than just one.

Similar #379 for creation of RO:0013002 'receives synaptic input in' and RO:0013003 'sends synaptic output to'.

Ideal term labels would be 'receives synaptic input from' and 'sends synaptic output to', but 'sends synaptic output to' is already used for RO:0013003.

We could rename 'sends synaptic output to' -> 'sends synaptic output into' (which makes it clearer that it refers to a region)

Alternatively labels could be 'strongly synapsed to' and 'strongly synapsed by' or similar.

Definitions to mirror RO:0013002 'receives synaptic input in' and RO:0013003 'sends synaptic output to' as well as parent classes:
from relationship: "A relationship between an anatomical structure (including cells) and a neuron that has a functionally relevant number of chemical synapses to it."
to relationship: "A relationship between a neuron and an anatomical structure (including cells) that it has a functionally relevant number of chemical synapses to."

@dosumis

### PR DESCRIPTION
**Pull request by Clare72**
fixes #455 
After a little more thought, I went with 'synaptic input partner of' and 'synaptic output partner of' for labels, but open to other suggestions.

### CODE REVIEW

**Review by dosumis — CHANGES_REQUESTED** [review]
All looks good apart from names, which I think are too confusing.  

Suggested fix:

Use names currently used for regions but modify to include object type in name

'receives synaptic input in'

\> 
 receives synaptic input from neuron
'receives synaptic input in region

'sends synaptic output to'
\> 
'sends synaptic output to neuron
'sends synaptic output to region

**Comment by Clare72** [comment]
> 'sends synaptic output to neuron'

just thought of a problem with this - object of synapsed_to can be a muscle.

so maybe we just stick to adding 'region' to region relationships and use 'sends synaptic output to' and 'receives synaptic output from' for new relationships

**Comment by matentzn** [comment]
What needs to be done here? We are scheduling an RO release for tomorrow, if you want this in, best finish :)

**Comment by dosumis** [comment]
Maybe 'neuron' -> 'cell' ?

**Review by dosumis — APPROVED** [review]

**Comment by Clare72** [comment]
So should we also change:
>between a neuron and an anatomical structure (including cells)

to:
>between a neuron and a cell

for 'sends synaptic output to cell'?

btw this would require terms for muscle cells (as we have in FBbt) and would be unsuitable for terms referring to 'complete' muscles.

**Comment by dosumis** [comment]
> So should we also change:
> 
> between a neuron and an anatomical structure (including cells)
> 
> to:
> 
> between a neuron and a cell
> 
> for 'sends synaptic output to cell'?
> 
> btw this would require terms for muscle cells (as we have in FBbt) and would be unsuitable for terms referring to 'complete' muscles.

I think this is OK in the text def maybe with a gloss to clarify.  Strictly each individual NMJ is between a neuron and a (syncytial) muscle cell (myotube).  I don't know if a single motor neuron can form NMJs with multiple myotube.  I think we need to avoid having the range of the relation be 'cell' though, given we don't (can't) name individual cells in vertebrates.

**Comment by matentzn** [comment]
Ready for merging?

**Review by dosumis — APPROVED** [review]

**Pull request merged**
