### PR TITLE
Relax the Range on RO_0002295

### PR DESCRIPTION
**Pull request by shawntanzk**
Change the range of RO to be anatomical entity instead 
Related to https://github.com/obophenotype/cell-ontology/issues/1782 (see CL ticket for reason)
Thanks to @gouttegd & @bvarner-ebi

### CODE REVIEW

**Comment by gouttegd** [comment]
The definition should be corrected as well, so that it no longer refers to an _anatomical structure_.

**Comment by wdduncan** [comment]
I am happy to put this on the agenda for the next RO meeting. Can you please hold off merging until then?

**Comment by cmungall** [comment]
I think this is good to merge, once Damien's comments are incorporated
(this could even go in a separate PR)

**Comment by shawntanzk** [comment]
> Damien's comments are incorporated

Already incorporated :) 

> I think this is good to merge

Alright, will merge, no need for taking up time in RO meeting then :) Thanks @cmungall

**Pull request merged**
